### PR TITLE
Improve doc

### PR DESCRIPTION
**Pull request by ericpre**
- [x] Fix building doc on unix.
- [x] Fix various error and warnings when building the doc.
- [x] Tweak formatting docstring.
- [x] Update web links in installation instructions.

The doc at http://hyperspy.org/hyperspyUI/ is not up to date, @francisco-dlp I guess this is one for you! ;)

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Actually I don't know how to upload the HyperSpyUI documentations. @vidartf, could you give us a hand with this?

**Comment by ericpre** [comment]
By looking at https://github.com/hyperspy/hyperspyUI/tree/gh-pages, it seems that it is using github-pages but I don't have access to the settings menu of this repo, so I can't comfirm. If this is case, it may upload the html code to http://hyperspy.org/hyperspyUI/ after each commit of the `gh-pages` branch?

**Comment by ericpre** [comment]
https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

humm, http://hyperspy.org/hyperspyUI/ does not use https...

**Comment by ericpre** [comment]
Merged this PR to try to update the website.

**Comment by ericpre** [comment]
> Actually I don't know how to upload the HyperSpyUI documentations. @vidartf, could you give us a hand with this?

See https://github.com/hyperspy/hyperspyUI/pull/192#issue-378977730.

**Pull request merged**
