### PR TITLE
Linux desktop integration

### PR DESCRIPTION
**Pull request by francisco-dlp**
To try it:

```bash
python -m hyperspyui.desktop_integration_linux
```

### CODE REVIEW

**Comment by vidartf** [comment]
I'll look in more detail later, but just from a read through, I wondered if the `xdg-icon-resource` lines of the [existing script](https://github.com/hyperspy/hyperspyUI/blob/92db330e3a3c49934ac2b77f389ddf6e6dd353e8/bin/hyperspyui_reg_linux_extensions.sh) are unneeded.

**Comment by francisco-dlp** [comment]
Sorry that I didn't realise that there was already a script for this.

Regarding registering the icon, it is unnecessary for the application icon, but it can be useful to associate the icon with e.g. the hspy files.

Although both scripts do the job, this one is written in Python and registers all the formats supported by hyperspy automatically. If you agree to keep this one, I'll update it to also register the icon and associate it to the hspy files. Also I could make it more modular, so that it can be imported and used to register extra formats.

**Comment by vidartf** [comment]
> Sorry that I didn't realise that there was already a script for this.

Don't be, the previous script was poorly tested, so having someone native to Linux take a stab at it is always better. I just wanted to point it out to ensure that you could pick the best parts of the two :)

Please go a head with the solutions you think best!

**Comment by francisco-dlp** [comment]
Done!

**Comment by vidartf** [comment]
Looks good to me, and I'll trust you on the testing, but do you think we should integrate it with the existing `desktop_integration` module? E.g. rename it with an underscore and then add an if branch in the current integration that would call out to this (maybe also split out the window bit to a file)? It's just the final polish, so I don't care a lot either way, but it might be nice to have a single entry point.

**Comment by francisco-dlp** [comment]
Sounds good to me, I'll take care of it if you like.

By the way, isn't there MacOS integration yet?

**Comment by vidartf** [comment]
@thomasaarholt did some initial work for getting it set up as an app. I cannot find any issue/PR on it though, so it might have only been over chat. Any input @thomasaarholt ?

**Comment by thomasaarholt** [comment]
I've essentially got an "app" wrapper for calling it through the terminal. The hyperspy logo has already been incorporate as an icon on it, but I'm entirely unfamiliar with how to package it as an application.

I was surprised to find out that on windows it did not require the terminal to be running constantly. What is the mechanism behind this? Is "Desktop integration" a common name for this in python?

**Comment by vidartf** [comment]
On windows you can use `pythonw`, and from a quick google it seems like that option is also available on Mac?

**Comment by francisco-dlp** [comment]
[py2app](https://pypi.python.org/pypi/py2app/) seems to offer an easy path to MacOS desktop integration.

**Comment by francisco-dlp** [comment]
Although it actually does a lot more than we need, so it may not be a good fit for purpose, sorry for the noise.

**Comment by vidartf** [comment]
> Sounds good to me, I'll take care of it if you like.

Yes, please. Getting the entry points right on the first go is really preferable!

**Comment by ericpre** [comment]
@francisco-dlp: it is not far from being finished (move code to `hyperspyui/desktop_integration.py`) and it seems to be working fine.
Also, would it be worth adding a command to uninstall the desktop integration?

**Comment by francisco-dlp** [comment]
OK, I'll finish this tomorrow.

**Pull request merged**
