### PR TITLE
New plugin: Style editor

### PR DESCRIPTION
**Pull request by vidartf**
Adds a style editor (Settings -> Edit style).

### CODE REVIEW

**Comment by thomasaarholt** [comment]
I checked this out on Windows and it worked fine, but on Mac I couldn't see the plugin at first. I tried unchecking it in the plugin manager and then rechecking it, but it won't recheck. The terminal shows this error:

```python
DEBUG:hyperspyui:Initializing plugin: <class 'hyperspyui.plugins.stylesheet.StylePlugin'>
Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/pluginmanager.py", line 238, in load
    p = self._load_if_enabled(plugin_type)
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/pluginmanager.py", line 230, in _load_if_enabled
    p = p_type(self.ui)
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/plugins/stylesheet.py", line 49, in __init__
    self.apply_styles()
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/plugins/stylesheet.py", line 64, in apply_styles
    QApplication.instance().setStyleSheet(self.settings['_style'])
TypeError: setStyleSheet(self, object): argument 1 has unexpected type 'QPyNullVariant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/widgets/pluginmanagerwidget.py", line 102, in setData
    self.plugin_manager.enable_plugin(name, enabled)
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/pluginmanager.py", line 100, in enable_plugin
    self.load(ptype)
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/pluginmanager.py", line 248, in load
    self.warn(sys._getframe().f_code.co_name, p.name)
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by vidartf** [comment]
I added a commit that should (hopefully) fix that issue.

**Comment by vidartf** [comment]
Any luck? :)

**Comment by thomasaarholt** [comment]
Will try after dinner!

**Comment by thomasaarholt** [comment]
Styles is now shown, but your suggested style didn't do anything. Can you give me a style that should definitely work, just to test that the style editor actually works?

**Comment by thomasaarholt** [comment]
Style editor definitely working on Mac, tested with 
`
QDockWidget
{
    color: red;
}
`

**Comment by vidartf** [comment]
Okies, merging this then.

**Pull request merged**
